config/routes.rb
Herbage::Application.routes.draw do

  devise_for :gardeners

  resources :seeds
  resources :plants

  root :to => 'home#index'
end

app/models/gardener.rb
class Gardener < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/plant.rb
# == Schema Information
#
# Table name: plants
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  common_names        :string(255)
#  origin              :string(255)
#  dimensions          :string(255)
#  cultural_conditions :string(255)
#  flowering_season    :string(255)
#  colour              :string(255)
#  growth_rate         :string(255)
#  foliage_colour      :string(255)
#  potential_use       :string(255)
#  potential_style     :string(255)
#  comments_care       :text
#  description         :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Plant < ActiveRecord::Base

  validates :name, :uniqueness => {:message => 'already exists'}

  validates :name, :colour, :presence => {:message => 'is a required field'}

  validates :description, :comments_care, :presence => {:message => 'needs to be filled in'}
end

app/models/seed.rb
class Seed < ActiveRecord::Base
  attr_accessible :name, :source, :sowing_time, :species
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_filter :authenticate_gardener!, :except => [:index, :show]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plants }
    end
  end

  # GET /plants/search?
  # GET /plants/
  def search
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plant }
    end
  end

  # GET /plants/new
  # GET /plants/new.json
  def new
    @plant = Plant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plant }
    end
  end

  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render json: @plant, status: :created, location: @plant }
      else
        format.html { render action: "new" }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.json
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController
  # GET /seeds
  # GET /seeds.json
  def index
    @seeds = Seed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seeds }
    end
  end

  # GET /seeds/1
  # GET /seeds/1.json
  def show
    @seed = Seed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/new
  # GET /seeds/new.json
  def new
    @seed = Seed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/1/edit
  def edit
    @seed = Seed.find(params[:id])
  end

  # POST /seeds
  # POST /seeds.json
  def create
    @seed = Seed.new(params[:seed])

    respond_to do |format|
      if @seed.save
        format.html { redirect_to @seed, notice: 'Seed was successfully created.' }
        format.json { render json: @seed, status: :created, location: @seed }
      else
        format.html { render action: "new" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seeds/1
  # PUT /seeds/1.json
  def update
    @seed = Seed.find(params[:id])

    respond_to do |format|
      if @seed.update_attributes(params[:seed])
        format.html { redirect_to @seed, notice: 'Seed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seeds/1
  # DELETE /seeds/1.json
  def destroy
    @seed = Seed.find(params[:id])
    @seed.destroy

    respond_to do |format|
      format.html { redirect_to seeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardener/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.haml
%h2 Herbage

%p Herbage is a tool for managing your home garden.

%p Track - Keep details about what you've planted, what worked and what didn't work out.

%p Share - Share post and tips about what you're growning and things you've found that work. Follow what other people are planting and

%p Learn - Keep a garden diary

%p Tools - Use tools to track when to plant, crop rotation and companion planting.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Herbage
    %meta{:charset => 'UTF-8'}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div.container
      %div.navbar.navbar-fixed-top.navbar-inverse
        %div.navbar-inner
          %div.container
            %a= link_to 'Herbage', root_path, class: 'brand'
            %ul.nav
              %li= link_to "Browse Plants", plants_path, class: 'active'
              %li= link_to "Browse Seeds",  seeds_path,  class: 'active'
              %li= link_to "Planning", "#", class: 'active'
      %div.row
        - if notice
          %p.notice
            = notice
        - if alert
          %p.alert
            = alert
        %div.span9
          = yield

app/views/plants/_form.html.haml
= simple_form_for @plant, :html => {:class => 'form-horizontal'} do |f|
  = f.input :name
  = f.input :common_names
  = f.input :genus
  = f.input :description, :input_html => { :class => "span6" }
  = f.input :colour
  = f.input :comments_care, :input_html => { :class => "span6" }
  = f.input :dimensions, :input_html => {:placeholder => '400x50cm'}
  = f.input :flowering_season, :input_html => {:placeholder => 'eg Late Spring'}
  = f.input :foliage_colour
  = f.input :potential_use, :input_html => {:placeholder => 'eg Cottage, Tropical'}
  = f.input :potential_style

  %div.control-group
    %div.controls
      = f.button :submit

app/views/plants/edit.html.haml
%h1= 'Editing plant'

= render :partial => 'form', :plant => @plant

= link_to 'Show', @plant
= link_to 'Back', plants_path

app/views/plants/index.html.haml
%h1= 'Listing plants'

%p
  = link_to 'New Plant', new_plant_path, :class => 'btn'

%table.table.table-striped
  %tr
    %th= 'Name'
    %th= 'Common names'
    %th= 'Species'
    %th= 'Genus'
    %th= 'Description'
    %th= 'Care'
    %th= 'Soil'
    %th= 'Position'
    %th= 'Colour'
    %th
    %th
    %th
  - @plants.each do |plant|
    %tr
      %td= plant.name
      %td= plant.common_names
      %td= plant.species
      %td= plant.genus
      %td= truncate plant.description
      %td= truncate plant.comments_care
      %td= plant.soil
      %td= plant.position
      %td= plant.colour
      %td= link_to 'Show', plant, :class => 'btn btn-mini'
      %td= link_to 'Edit', edit_plant_path(plant), :class => 'btn btn-mini'
      %td= link_to 'Destroy', plant, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger'

app/views/plants/new.html.haml
%h1 New plant

= render :partial => 'form', :plant => @plant

= link_to 'Back', plants_path

app/views/plants/show.html.haml
%h1= @plant.name

%p
  %b= 'Name:'
  = @plant.name

%p
  %b= 'Common names:'
  = @plant.common_names

%p
  %b= 'Genus:'
  = @plant.genus

%p
  %b= 'Colour:'
  = @plant.colour

%p
  %b= 'Description:'
  = @plant.description

%p
  %b= 'Care:'
  = @plant.comments_care

%p
  %b= 'Soil:'
  = @plant.soil

%p
  %b= 'Position:'
  = @plant.position


= link_to 'Edit', edit_plant_path(@plant)
= link_to 'Back', plants_path

app/views/seeds/_form.html.haml
= simple_form_for(@seed) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :source
    = f.input :sowing_time
    = f.input :species

  .form-actions
    = f.button :submit

app/views/seeds/edit.html.haml
%h1 Editing seed

= render 'form'

= link_to 'Show', @seed
\|
= link_to 'Back', seeds_path

app/views/seeds/index.html.haml
%h1 Listing seeds

%table
  %tr
    %th Name
    %th Source
    %th Sowing time
    %th Species
    %th
    %th
    %th

  - @seeds.each do |seed|
    %tr
      %td= seed.name
      %td= seed.source
      %td= seed.sowing_time
      %td= seed.species
      %td= link_to 'Show', seed
      %td= link_to 'Edit', edit_seed_path(seed)
      %td= link_to 'Destroy', seed, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Seed', new_seed_path

app/views/seeds/new.html.haml
%h1 New seed

= render 'form'

= link_to 'Back', seeds_path

app/views/seeds/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @seed.name
%p
  %b Source:
  = @seed.source
%p
  %b Sowing time:
  = @seed.sowing_time
%p
  %b Species:
  = @seed.species

= link_to 'Edit', edit_seed_path(@seed)
\|
= link_to 'Back', seeds_path